name: hello-world
on: push
jobs:
  my-testing:
      runs-on: ubuntu-latest
      steps:
        - name: List directory
        - run: ls -la
        - uses: actions/checkout@v3
        - name: Print Hello Message
          run: |
            make say-hello
            ls -la
        


