name: hello-world
on: push
jobs:
  my-testing:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Print Hello Message
          run: make say-hello
        


